import type { Metadata } from "next";
import Image from "next/image";
import logo from "@/public/niagads-logo.svg"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@niagads/ui";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
            <Header 
                logo={
                    <figure>
                        <Image width={200} height={60} src={logo} alt="Niagads GenomicsDB logo" />
                    </figure>
                }
                links={[
                    {text: "About Us", url: ""},
                    {text: "Publications", url: ""},
                    {text: "Cite and Acknowledge", url: ""},
                    {text: "Help", url: ""},
                ]}
            />
            <body className="content-container">{children}</body>
        </html>
    );
}
